# Generated by Django 4.1.7 on 2023-04-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0002_alter_profile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reference_id',
            field=models.CharField(default=1001, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
