# Generated by Django 4.1.7 on 2023-04-16 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0003_complaint_reference_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='collegename',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('City1', 'City1'), ('City2', 'City2')], default=django.utils.timezone.now, max_length=29),
            preserve_default=False,
        ),
    ]
