# Generated by Django 4.1.7 on 2023-05-30 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0004_remove_profile_collegename_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('Lucknow', 'Lucknow'), ('Kanpur', 'Kanpur')], max_length=29),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contactnumber',
            field=models.IntegerField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format:Up to 10 digits allowed.', regex='^\\d{10,10}$')]),
        ),
    ]
