# Generated by Django 4.1.7 on 2023-05-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0005_alter_profile_city_alter_profile_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Type_of_complaint',
            field=models.CharField(choices=[('Management', 'Management'), ('College', 'College'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
